"""Mock report agent for Phase 1 scaffold."""

from __future__ import annotations

from app.observability import traced
from app.state import ApplicationState


@traced("report_agent")
def report_agent(state: ApplicationState) -> dict[str, object]:
    """Generate placeholder applicant and internal reports."""
    decision = state.get("decision", "REVIEW")
    return {
        "status": "reported",
        "report_applicant": f"Your application is currently marked as {decision}. We will follow up soon.",
        "report_internal": (
            "# Internal Report\n\n"
            f"- Decision: {decision}\n"
            f"- Evaluation score: {state.get('evaluation_score', 72.0)}\n"
            "- Notes: Placeholder report generated by scaffold.\n"
        ),
    }
